id: A184494B9
title: A Prayer for the Long Life of Ngawang Kunga Tekchen Palbar Trinlé Wangi Gyalpo,
  the Lord of Refuge and Precious Holder of the Throne of the Drolma Palace at Glorious
  Sakya
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:28:40.480224
  last_modified_at: 2022-03-01 01:28:40.480231
